server:
  port: 8001
spring:
  application:
    name: edu-aliyun-oss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
# 阿里云oss配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      accessKeyId: LTAI4FtxWtr8qX1yTi2xjPKR
      accessKeySecret: w0qA36wu5SiLX9BAmITyC0l8BbDEVe
      bucket: edu-01
# 配置注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
