server:
  port: 8001
spring:
  application:
    name: edu-oss
  profiles:
    active: dev

# 阿里云oss配置
aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      accessKeyId: LTAI4FtxWtr8qX1yTi2xjPKR
      accessKeySecret: w0qA36wu5SiLX9BAmITyC0l8BbDEVe
      bucket: edu-01
      fileHost: avatar # 存储的文件夹